---
- name: Remove not-Docker-config folder.
  file:
    path: /root/.docker/config.json/
    state: absent

- name: Check if static assets folder is a symlink.
  stat:
    path: /var/lib/awx/public/static/
  register: sites_available

- name: Remove existing static assets folder.
  file:
    path: /var/lib/awx/public/static/
    state: absent

- name: Symlink awx UI folder into place.
  file:
    dest: /var/lib/awx/public/static
    src: /usr/lib/python2.7/site-packages/awx/ui/static
    state: link
